/**
 * Table ownership map (ARCHITECTURE section 1.1, rule 3): exactly one module may read/write each
 * Prisma model. `reporting` may SELECT anything; `audit_log`/`domain_event` are written through
 * platform helpers only. A CI script that walks imports against this map is a later step.
 */
export const ownership = {
  Tenant: 'tenancy',
  User: 'tenancy',
  PlatformAdmin: 'tenancy',
  Session: 'tenancy',
  Customer: 'registry',
  Contact: 'registry',
  Building: 'registry',
  Elevator: 'registry',
  Contract: 'registry',
  ContractElevator: 'registry',
  ImportBatch: 'registry',
  DeviceEnrollmentToken: 'tenancy',
  Visit: 'visits',
  VisitTechnician: 'visits',
  ChecklistTemplate: 'maintenance',
  Attachment: 'documents',
  VisitAttachment: 'documents',
  InvoiceSequence: 'billing',
  Invoice: 'billing',
  Payment: 'billing',
  Callback: 'callbacks',
  CallbackEvent: 'callbacks',
  Defect: 'defects',
  Inspection: 'calendar',
  AlarmDeviceTest: 'calendar',
  NotificationTemplate: 'notifications',
  NotificationRule: 'notifications',
  Notification: 'notifications',
  ExportJob: 'reporting',
  ReportRun: 'reporting',
  DomainEvent: 'platform',
  EventDelivery: 'platform',
  JobRun: 'platform',
  AuditLog: 'platform',
  IdempotencyKey: 'platform',
} as const

export type ModelName = keyof typeof ownership

/** Models that carry a NOT NULL tenantId and must never be queried without it. */
export const tenantOwnedModels: ReadonlySet<string> = new Set<ModelName>([
  'User',
  'Customer',
  'Contact',
  'Building',
  'Elevator',
  'Contract',
  'ContractElevator',
  'ImportBatch',
  'DeviceEnrollmentToken',
  'Visit',
  'VisitTechnician',
  'Attachment',
  'VisitAttachment',
  'IdempotencyKey',
  'InvoiceSequence',
  'Invoice',
  'Payment',
  'Callback',
  'CallbackEvent',
  'Defect',
  'Inspection',
  'AlarmDeviceTest',
  'NotificationRule',
  'Notification',
  'ExportJob',
  'ReportRun',
])
